import 'dart:async';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'package:url_launcher/url_launcher.dart';
import '../providers/transaction_provider.dart';
import '../providers/expense_provider.dart';
import '../providers/business_profile_provider.dart';

class ReportsScreen extends StatelessWidget {
  const ReportsScreen({super.key});

  Future<void> _sendReportToWhatsApp(BuildContext context, double dailySales, double totalSaved) async {
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMM yyyy').format(now);
    
    final report = '''
📊 *DAILY REPORT - $dateStr*

💰 *Daily Sales:* UGX ${NumberFormat('#,###').format(dailySales)}
🏦 *Total Savings:* UGX ${NumberFormat('#,###').format(totalSaved)}

---
*Report generated by Local POS*
''';
    
    final whatsappUrl = Uri.parse('https://wa.me/?text=${Uri.encodeComponent(report)}');
    
    if (await canLaunchUrl(whatsappUrl)) {
      await launchUrl(whatsappUrl, mode: LaunchMode.externalApplication);
    } else {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Could not open WhatsApp')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PERFORMANCE'),
      ),
      body: Consumer3<TransactionProvider, ExpenseProvider, BusinessProfileProvider>(
        builder: (context, transactionProvider, expenseProvider, profileProvider, child) {
          final transactions = transactionProvider.transactions;
          
          // Calculate daily sales
          final now = DateTime.now();
          final today = DateTime(now.year, now.month, now.day);
          double dailySales = 0.0;
          for (var tx in transactions) {
            final txDate = DateTime(tx.date.year, tx.date.month, tx.date.day);
            if (txDate.isAtSameMomentAs(today)) {
              dailySales += tx.total;
            }
          }
          
          final totalSaved = profileProvider.profile?.totalSavings ?? 0.0;
          
          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Card(
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('DAILY SALES',
                                  style: TextStyle(color: Colors.grey[600])),
                              const SizedBox(height: 8),
                              Text(
                                'UGX ${NumberFormat('#,###').format(dailySales)}',
                                style: const TextStyle(
                                    fontSize: 24, fontWeight: FontWeight.bold),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Card(
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('TOTAL SAVED',
                                  style: TextStyle(color: Colors.green[600])),
                              const SizedBox(height: 8),
                              Text(
                                'UGX ${NumberFormat('#,###').format(totalSaved)}',
                                style: const TextStyle(
                                    fontSize: 24, fontWeight: FontWeight.bold, color: Colors.green),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
                Card(
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text('7-DAY REVENUE TREND'),
                        const SizedBox(height: 16),
                        SizedBox(
                          height: 200,
                          child: Center(
                            child: Text(
                              'Chart coming soon',
                              style: TextStyle(color: Colors.grey[600]),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                ElevatedButton.icon(
                  onPressed: () => _sendReportToWhatsApp(context, dailySales, totalSaved),
                  icon: const Icon(Icons.share),
                  label: const Text('SEND REPORT TO WHATSAPP'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF00897B),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
